# Site settings
title: lovesigma
email: kunyoung.shin@nhnent.com
description: > # 기술블로그
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lovesigma.github.io" # the base hostname & protocol for your site
twitter_username: lovesigma
github_username: lovesigma

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]